### ISSUE TITLE
"cannot allocate memory in static TLS" (Centos 6.10)

### ISSUE THREAD

**Issue by bsutherland-sh** [build2/libbutl#2]
During installation of build2 using the recommended method on Centos 6.10:

```
+ bpkg-stage --version
bpkg-stage: error while loading shared libraries: /usr/local/lib/libbutl-stage-0.13.so: cannot allocate memory in static TLS block
```

Any assistance would be appreciated.

**Comment by boris-kolpackov** [comment]
I don't think this can be fixed by modifying compiler flags (there are fuzzy suggestions in that linked bug report but I can't glean anything conclusive from that).

In the meantime we've added the workaround in the code and it is available in the latest staged toolchain. Can you give it a try and see if you are able to build and use build2 on this platform: https://build2.org/community.xhtml#stage

**Comment by bsutherland-sh** [comment]
Hi Boris,

Good news! Seems like that's solved the problem reported. Unfortunately, I've hit another issue. The error is:

```
error: inconsistent C++ compiler behavior
  info: run the following two commands to investigate
```

Then two g++ command lines are listed. Would you like me to open a separate issue for that?

**Comment by boris-kolpackov** [comment]
This error is normally due to insufficient disk space. You need about 1GB during the installation; see the FAQ for details: https://build2.org/install-faq.xhtml#requirements

If this is not it, then yes, please, open a new issue (should go to the `build2` project). I am also going to close this one as it seems the workaround did the trick.
